/*
 * generated by Xtext 2.10.0
 */
package org.structs4java.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class Structs4JavaDslUiModule extends AbstractStructs4JavaDslUiModule {
}
