/*
 * This source file was generated by the Gradle 'init' task
 */
package org.structs4java;

import java.io.File;
import java.io.IOException;
import java.io.Writer;
import java.io.FileWriter;
import java.nio.file.Files;
import org.gradle.testkit.runner.GradleRunner;
import org.gradle.testkit.runner.BuildResult;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.*;

/**
 * A simple functional test for the 'org.example.greeting' plugin.
 */
class Structs4javaGradlePluginFunctionalTest {
    @TempDir
    File projectDir;

    private File getBuildFile() {
        return new File(projectDir, "build.gradle");
    }

    private File getSettingsFile() {
        return new File(projectDir, "settings.gradle");
    }

    private File getStructsFile() {
        return new File(projectDir, "example.structs");
    }

    @Test void canRunTask() throws IOException {
        writeString(getSettingsFile(), "");
        writeString(getBuildFile(), """
            plugins {
                id('com.github.marc-christian-schulze.structs4java')
            }
            
            compileStructs {
                structFiles = fileTree(dir: '.', include: '**/*.structs')
                outputDirectory = file("${buildDir}/generated-sources/structs")
            }
            """);
        writeString(getStructsFile(), """
            struct Example {
            
            }    
            """);

        // Run the build
        GradleRunner runner = GradleRunner.create();
        runner.forwardOutput();
        runner.withPluginClasspath();
        runner.withArguments("compileStructs", "--info");
        runner.withProjectDir(projectDir);
        BuildResult result = runner.build();

        // Verify the result
        assertTrue(result.getOutput().contains("Found struct file:"));
        assertTrue(result.getOutput().contains("/example.structs"));
    }

    private void writeString(File file, String string) throws IOException {
        try (Writer writer = new FileWriter(file)) {
            writer.write(string);
        }
    }
}
