/*
 * generated by Structs4Java 2.14.0
 */
package org.structs4java.ide


/**
 * Use this class to register ide components.
 */
class Structs4JavaDslIdeModule extends AbstractStructs4JavaDslIdeModule {
}
