/*
 * This source file was generated by the Gradle 'init' task
 */
package org.structs4java;

import org.gradle.api.Project;
import org.gradle.api.Plugin;

/**
 * A simple 'hello world' plugin.
 */
public class Structs4javaGradlePlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.getTasks().register("compileStructs", CompileStructsTask.class);
    }
}
