/*
 * This source file was generated by the Gradle 'init' task
 */
package org.structs4java;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * A simple unit test for the 'org.example.greeting' plugin.
 */
class Structs4javaGradlePluginTest {
    @Test void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("com.github.marc-christian-schulze.structs4java");

        // Verify the result
        assertNotNull(project.getTasks().findByName("compileStructs"));
    }
}
