/*
 * generated by Xtext 2.10.0
 */
package org.structs4java.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.structs4java.structs4JavaDsl.Model

@RunWith(XtextRunner)
@InjectWith(Structs4JavaDslInjectorProvider)
class Structs4JavaDslParsingTest{

	@Inject
	ParseHelper<Model> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
