/*
 * generated by Xtext 2.10.0
 */
package org.structs4java


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Structs4JavaDslStandaloneSetup extends Structs4JavaDslStandaloneSetupGenerated {

	def static void doSetup() {
		new Structs4JavaDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
