name: CI on master

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # required for github-action-get-previous-tag

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.6

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Maven
      uses: GabrielBB/xvfb-action@v1
      with:
        run: mvn clean install -Dmaven.repo.local=./.m2 -Declipse.p2.mirrors=false

    - name: Build with Gradle
      run: cd ./structs4java-gradle-plugin && ./gradlew build
